server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:}
      database: ${MONGODB_DATABASE:dfrm}
  jackson:
    time-zone: Europe/Stockholm
    serialization:
      write-dates-as-timestamps: false
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  mail:
    default-encoding: UTF-8
    host: ${SMTP_HOST:example.com}
    username: ${SMTP_USER:example@example.com}
    password: ${SMTP_PASS:}
    port: ${SMTP_PORT:587}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  web:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: "*"
      allow-credentials: true

jwt:
  secret: ${ACCESS_TOKEN_SECRET:}
  expiration: 86400000

mail:
  imap:
    host: ${EMAIL_HOST:example.com}
    port: ${EMAIL_PORT:993}
    username: ${EMAIL_USER:example@example.com}
    password: ${EMAIL_PASSWORD:}

google:
  translate:
    api:
      key: ${GOOGLE_TRANSLATE_API_KEY:}

logging:
  level:
    com.dfrm: DEBUG
    org.springframework:
      data.mongodb: DEBUG
      security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 