server:
  port: ${PORT:8080}

spring:
  jackson:
    time-zone: Europe/Stockholm
    serialization:
      write-dates-as-timestamps: false
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  mail:
    default-encoding: UTF-8
    host: ${SMTP_HOST:mailcluster.loopia.se}
    username: ${SMTP_USER:info@duggalsfastigheter.se}
    password: ${SMTP_PASS:!e8E$..n2MP2W_7}
    port: ${SMTP_PORT:587}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  web:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: "*"
      allow-credentials: true

jwt:
  secret: ${ACCESS_TOKEN_SECRET:DLMA/BDb+lF2rmS7TlxWAjBaKQmxAP4JNAmca9ltoLo=}
  expiration: 86400000

mail:
  imap:
    host: ${EMAIL_HOST:mailcluster.loopia.se}
    port: ${EMAIL_PORT:993}
    username: ${EMAIL_USER:felanmalan@duggalsfastigheter.se}
    password: ${EMAIL_PASSWORD:EFtXeWpTXtn4d@?}

google:
  translate:
    api:
      key: ${GOOGLE_TRANSLATE_API_KEY:AIzaSyB5ngQA09xhKB48kWqs5Dm0-LjWNNf2Tfk}

logging:
  level:
    com.dfrm: DEBUG
    org.springframework:
      data.mongodb: DEBUG
      security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 